CC = g++
T1 = main
T2 = Rainbow
T3 = 1_gampang
T4 = A

FLAG = -std=c++11

all: $(T1).cpp $(T2).cpp $(T3).cpp $(T4).cpp 
	$(CC) $(FLAG) -c $(T1).cpp $(T2).cpp $(T3).cpp $(T4).cpp 
	$(CC) $(FLAG) -o $(T1) $(T1).o $(T2).o $(T3).o $(T4).o 
